export interface Car {
  id: string
  make: string
  model: string
  year: number
  price: number
  mileage: number
  engine: string
  fuel: string
  fuelUa: string
  drive: string
  bodyType: string
  bodyTypeUa: string
  color: string
  colorUa: string | null
  transmission: string
  horsepower: number
  status: "In Stock" | "In Transit" | "Reserved" | "Sold" | "Verified"
  statusUa: string
  verified: boolean
  image: string
  gallery: string[]
  features: string[]
  featuresUa: string[]
  vin: string | null
  doors: number | null
  seats: number | null
  seatMaterial: string | null
  seatMaterialUa: string | null
  safetyFeatures: string[]
  comfortFeatures: string[]
  infotainment: string[]
  condition: string
  conditionUa: string | null
  country: string
  countryUa: string | null
  plateType: string | null
  sourceType?: "stock" | "parser_hot" | "parser_custom"
  history: {
    date: string
    event: string
    eventUa: string
    mileage: number
  }[]
}

// Returns null for missing/unknown placeholder values from the parser
function nv(v: unknown): string | null {
  if (v == null) return null
  const s = String(v).trim()
  const lower = s.toLowerCase()
  if (!s || lower === "unknown" || lower === "невідомо") return null
  return s
}

export function mapDbCar(row: Record<string, unknown>): Car {
  return {
    id: row.id as string,
    make: row.make as string,
    model: row.model as string,
    year: row.year as number,
    price: Number(row.price),
    mileage: row.mileage as number,
    engine: nv(row.engine) as string,
    fuel: nv(row.fuel) as string,
    fuelUa: nv(row.fuel_ua) as string,
    drive: nv(row.drive) as string,
    bodyType: nv(row.body_type) as string,
    bodyTypeUa: nv(row.body_type_ua) as string,
    color: nv(row.color) as string,
    colorUa: nv(row.color_ua),
    transmission: nv(row.transmission) as string,
    horsepower: row.horsepower as number,
    status: row.status as Car["status"],
    statusUa: row.status_ua as string,
    verified: (row.verified as boolean) ?? false,
    image: row.image as string,
    gallery: (row.gallery as string[]) ?? [],
    features: (row.features as string[]) ?? [],
    featuresUa: (row.features_ua as string[]) ?? [],
    vin: nv(row.vin),
    doors: (row.doors as number) ?? null,
    seats: (row.seats as number) ?? null,
    seatMaterial: nv(row.seat_material),
    seatMaterialUa: nv(row.seat_material_ua),
    safetyFeatures: (row.safety_features as string[]) ?? [],
    comfortFeatures: (row.comfort_features as string[]) ?? [],
    infotainment: (row.infotainment as string[]) ?? [],
    condition: nv(row.condition) as string,
    conditionUa: nv(row.condition_ua),
    country: nv(row.country) as string,
    countryUa: nv(row.country_ua),
    plateType: nv(row.plate_type),
    sourceType: row.source_type as Car["sourceType"],
    history: (row.history as Car["history"]) ?? [],
  }
}

export const cars: Car[] = [
  {
    id: "1",
    make: "Porsche",
    model: "911 GT3 RS",
    year: 2024,
    price: 241300,
    mileage: 1200,
    engine: "4.0L Flat-6",
    fuel: "Petrol",
    fuelUa: "Бензин",
    drive: "RWD",
    bodyType: "Coupe",
    bodyTypeUa: "Купе",
    color: "GT Silver Metallic",
    colorUa: "GT Сріблястий Металік",
    transmission: "7-Speed PDK",
    horsepower: 518,
    status: "In Stock",
    statusUa: "В наявності",
    verified: true,
    image: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=1200&q=90",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=90",
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200&q=90",
    ],
    features: ["Carbon Ceramic Brakes", "Sport Chrono Package", "Bucket Seats", "Rear Axle Steering"],
    featuresUa: ["Карбон-керамічні гальма", "Sport Chrono пакет", "Спортивні сидіння", "Заднє підруливання"],
    vin: "WP0AF2A91RS2XXXXX",
    doors: 2,
    seats: 2,
    seatMaterial: "Leather",
    seatMaterialUa: "Шкіра",
    safetyFeatures: ["ABS", "ESP", "6 Airbags", "ISOFIX", "Rear Camera"],
    comfortFeatures: ["Sport Chrono", "Heated Seats", "Electric Mirrors", "Auto Climate"],
    infotainment: ["Apple CarPlay", "Bose Sound", "Navigation", "Bluetooth"],
    condition: "Used",
    conditionUa: "Б/у",
    country: "Germany",
    countryUa: "Німеччина",
    plateType: "Євро номери",
    history: [
      { date: "2024-01", event: "Factory Production", eventUa: "Виробництво", mileage: 0 },
      { date: "2024-03", event: "Delivered to Dealer", eventUa: "Доставлено дилеру", mileage: 12 },
      { date: "2024-06", event: "First Registration", eventUa: "Перша реєстрація", mileage: 45 },
      { date: "2025-01", event: "Service Inspection", eventUa: "Сервісний огляд", mileage: 1200 },
    ],
  },
  {
    id: "2",
    make: "BMW",
    model: "M4 CSL",
    year: 2024,
    price: 148900,
    mileage: 3400,
    engine: "3.0L Twin-Turbo I6",
    fuel: "Petrol",
    fuelUa: "Бензин",
    drive: "RWD",
    bodyType: "Coupe",
    bodyTypeUa: "Купе",
    color: "Frozen Brooklyn Grey",
    colorUa: "Frozen Brooklyn Сірий",
    transmission: "8-Speed M Steptronic",
    horsepower: 543,
    status: "In Stock",
    statusUa: "В наявності",
    verified: true,
    image: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1200&q=90",
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=90",
    ],
    features: ["Carbon Fiber Roof", "M Carbon Bucket Seats", "Titanium Exhaust", "M Traction Control"],
    featuresUa: ["Карбоновий дах", "M Карбонові сидіння", "Титановий вихлоп", "M Контроль тяги"],
    vin: "WBS43AZ02R7YXXXXX",
    doors: 2,
    seats: 4,
    seatMaterial: "Alcantara",
    seatMaterialUa: "Алькантара",
    safetyFeatures: ["ABS", "ESP", "8 Airbags", "Lane Departure Warning", "Collision Warning"],
    comfortFeatures: ["Heated Seats", "Electric Seats", "Carbon Interior Trim", "Auto Climate"],
    infotainment: ["Apple CarPlay", "Android Auto", "Harman Kardon", "Navigation", "Wireless Charging"],
    condition: "Used",
    conditionUa: "Б/у",
    country: "Germany",
    countryUa: "Німеччина",
    plateType: "Євро номери",
    history: [
      { date: "2024-02", event: "Factory Production", eventUa: "Виробництво", mileage: 0 },
      { date: "2024-04", event: "Delivered to Dealer", eventUa: "Доставлено дилеру", mileage: 18 },
      { date: "2024-05", event: "First Registration", eventUa: "Перша реєстрація", mileage: 50 },
      { date: "2025-02", event: "Service Inspection", eventUa: "Сервісний огляд", mileage: 3400 },
    ],
  },
  {
    id: "3",
    make: "Mercedes-Benz",
    model: "AMG GT 63 S",
    year: 2024,
    price: 189500,
    mileage: 5600,
    engine: "4.0L Twin-Turbo V8",
    fuel: "Petrol",
    fuelUa: "Бензин",
    drive: "AWD",
    bodyType: "Sedan",
    bodyTypeUa: "Седан",
    color: "Obsidian Black",
    colorUa: "Обсидіан Чорний",
    transmission: "9-Speed AMG Speedshift",
    horsepower: 630,
    status: "Verified",
    statusUa: "Перевірено",
    verified: true,
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1200&q=90",
      "https://images.unsplash.com/photo-1520031441872-265e4ff70366?w=1200&q=90",
    ],
    features: ["AMG Performance Exhaust", "Burmester 3D Sound", "Active Aero", "Drift Mode"],
    featuresUa: ["AMG Performance вихлоп", "Burmester 3D звук", "Активна аеродинаміка", "Drift режим"],
    vin: "W1K6G7GB5RA1XXXXX",
    doors: 4,
    seats: 5,
    seatMaterial: "Leather",
    seatMaterialUa: "Шкіра",
    safetyFeatures: ["ABS", "ESP", "10 Airbags", "Active Brake Assist", "Blind Spot Assist", "PRE-SAFE"],
    comfortFeatures: ["Heated Seats", "Ventilated Seats", "Massage Seats", "Panoramic Roof", "Air Suspension"],
    infotainment: ["MBUX", "Apple CarPlay", "Android Auto", "Burmester 3D", "Navigation", "Head-Up Display"],
    condition: "Certified",
    conditionUa: "Сертифікований",
    country: "Germany",
    countryUa: "Німеччина",
    plateType: "Євро номери",
    history: [
      { date: "2023-11", event: "Factory Production", eventUa: "Виробництво", mileage: 0 },
      { date: "2024-01", event: "Delivered to Dealer", eventUa: "Доставлено дилеру", mileage: 22 },
      { date: "2024-02", event: "First Registration", eventUa: "Перша реєстрація", mileage: 60 },
      { date: "2025-01", event: "Full Service", eventUa: "Повне ТО", mileage: 5600 },
    ],
  },
  {
    id: "4",
    make: "Audi",
    model: "RS e-tron GT",
    year: 2025,
    price: 164400,
    mileage: 800,
    engine: "Dual Electric Motors",
    fuel: "Electric",
    fuelUa: "Електро",
    drive: "AWD",
    bodyType: "Sedan",
    bodyTypeUa: "Седан",
    color: "Daytona Grey",
    colorUa: "Daytona Сірий",
    transmission: "2-Speed Automatic",
    horsepower: 637,
    status: "In Transit",
    statusUa: "В дорозі",
    verified: true,
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&q=90",
    ],
    features: ["Matrix LED Headlights", "Air Suspension", "Carbon Optics Package", "Bang & Olufsen 3D"],
    featuresUa: ["Matrix LED фари", "Пневмопідвіска", "Карбон пакет", "Bang & Olufsen 3D"],
    vin: "WUAESFF21RB0XXXXX",
    doors: 4,
    seats: 4,
    seatMaterial: "Leather",
    seatMaterialUa: "Шкіра",
    safetyFeatures: ["ABS", "ESP", "8 Airbags", "Lane Assist", "Adaptive Cruise"],
    comfortFeatures: ["Heated Seats", "Ventilated Seats", "Air Suspension", "Matrix LED"],
    infotainment: ["MMI Touch", "Apple CarPlay", "Android Auto", "Bang & Olufsen", "Navigation"],
    condition: "New",
    conditionUa: "Новий",
    country: "Germany",
    countryUa: "Німеччина",
    plateType: "Без номерів",
    history: [
      { date: "2025-01", event: "Factory Production", eventUa: "Виробництво", mileage: 0 },
      { date: "2025-02", event: "Quality Inspection", eventUa: "Контроль якості", mileage: 5 },
    ],
  },
  {
    id: "5",
    make: "Lamborghini",
    model: "Huracan Tecnica",
    year: 2024,
    price: 328900,
    mileage: 2100,
    engine: "5.2L V10",
    fuel: "Petrol",
    fuelUa: "Бензин",
    drive: "RWD",
    bodyType: "Coupe",
    bodyTypeUa: "Купе",
    color: "Verde Mantis",
    colorUa: "Verde Mantis",
    transmission: "7-Speed LDF",
    horsepower: 631,
    status: "In Stock",
    statusUa: "В наявності",
    verified: true,
    image: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200&q=90",
    ],
    features: ["LDVI System", "Carbon Ceramic Brakes", "Rear-Wheel Steering", "Performance Traction Control"],
    featuresUa: ["Система LDVI", "Карбон-керамічні гальма", "Заднє підруливання", "Контроль тяги"],
    vin: "ZHWUE4ZF5RLA0XXXXX",
    doors: 2,
    seats: 2,
    seatMaterial: "Alcantara",
    seatMaterialUa: "Алькантара",
    safetyFeatures: ["ABS", "ESP", "4 Airbags", "Rear Camera", "Parking Sensors"],
    comfortFeatures: ["Heated Seats", "Electric Seats", "Lift System"],
    infotainment: ["Apple CarPlay", "Android Auto", "Navigation", "Telemetry"],
    condition: "Used",
    conditionUa: "Б/у",
    country: "Italy",
    countryUa: "Італія",
    plateType: "Євро номери",
    history: [
      { date: "2024-03", event: "Factory Production", eventUa: "Виробництво", mileage: 0 },
      { date: "2024-05", event: "Delivered to Dealer", eventUa: "Доставлено дилеру", mileage: 15 },
      { date: "2024-06", event: "First Registration", eventUa: "Перша реєстрація", mileage: 30 },
      { date: "2025-01", event: "Annual Service", eventUa: "Щорічне ТО", mileage: 2100 },
    ],
  },
  {
    id: "6",
    make: "Porsche",
    model: "Taycan Turbo S",
    year: 2025,
    price: 197400,
    mileage: 450,
    engine: "Dual Electric Motors",
    fuel: "Electric",
    fuelUa: "Електро",
    drive: "AWD",
    bodyType: "Sedan",
    bodyTypeUa: "Седан",
    color: "Frozen Blue",
    colorUa: "Frozen Blue",
    transmission: "2-Speed Automatic",
    horsepower: 750,
    status: "In Stock",
    statusUa: "В наявності",
    verified: true,
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=90",
    ],
    features: ["PCCB Brakes", "Rear Axle Steering", "Sport Chrono", "Burmester Sound"],
    featuresUa: ["PCCB гальма", "Заднє підруливання", "Sport Chrono", "Burmester звук"],
    vin: "WP0JA2Y11RSA0XXXXX",
    doors: 4,
    seats: 4,
    seatMaterial: "Leather",
    seatMaterialUa: "Шкіра",
    safetyFeatures: ["ABS", "ESP", "8 Airbags", "Lane Keep Assist", "Night Vision"],
    comfortFeatures: ["Heated Seats", "Ventilated Seats", "Air Suspension", "Panoramic Roof"],
    infotainment: ["PCM 6.0", "Apple CarPlay", "Burmester", "Navigation", "Head-Up Display"],
    condition: "New",
    conditionUa: "Новий",
    country: "Germany",
    countryUa: "Німеччина",
    plateType: "Без номерів",
    history: [
      { date: "2025-01", event: "Factory Production", eventUa: "Виробництво", mileage: 0 },
      { date: "2025-02", event: "Delivered", eventUa: "Доставлено", mileage: 20 },
    ],
  },
  {
    id: "7",
    make: "Ferrari",
    model: "296 GTB",
    year: 2024,
    price: 378500,
    mileage: 3800,
    engine: "3.0L Twin-Turbo V6 Hybrid",
    fuel: "Hybrid",
    fuelUa: "Гібрид",
    drive: "RWD",
    bodyType: "Coupe",
    bodyTypeUa: "Купе",
    color: "Rosso Corsa",
    colorUa: "Rosso Corsa",
    transmission: "8-Speed F1 DCT",
    horsepower: 818,
    status: "Reserved",
    statusUa: "Зарезервовано",
    verified: true,
    image: "https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=1200&q=90",
    ],
    features: ["Assetto Fiorano Package", "Carbon Fiber Wheels", "Manettino Dial", "Active Aero"],
    featuresUa: ["Пакет Assetto Fiorano", "Карбонові диски", "Manettino перемикач", "Активна аеродинаміка"],
    vin: "ZFF96CFA4R0XXXXXX",
    doors: 2,
    seats: 2,
    seatMaterial: "Leather",
    seatMaterialUa: "Шкіра",
    safetyFeatures: ["ABS", "ESP", "6 Airbags", "Rear Camera", "Parking Sensors"],
    comfortFeatures: ["Heated Seats", "Electric Seats", "Lift System", "Auto Climate"],
    infotainment: ["Apple CarPlay", "JBL Audio", "Navigation", "Telemetry"],
    condition: "Used",
    conditionUa: "Б/у",
    country: "Italy",
    countryUa: "Італія",
    plateType: "Євро номери",
    history: [
      { date: "2023-12", event: "Factory Production", eventUa: "Виробництво", mileage: 0 },
      { date: "2024-02", event: "Delivered to Dealer", eventUa: "Доставлено дилеру", mileage: 10 },
      { date: "2024-03", event: "First Registration", eventUa: "Перша реєстрація", mileage: 25 },
      { date: "2025-01", event: "Service Inspection", eventUa: "Сервісний огляд", mileage: 3800 },
    ],
  },
  {
    id: "8",
    make: "McLaren",
    model: "750S",
    year: 2024,
    price: 319800,
    mileage: 1900,
    engine: "4.0L Twin-Turbo V8",
    fuel: "Petrol",
    fuelUa: "Бензин",
    drive: "RWD",
    bodyType: "Coupe",
    bodyTypeUa: "Купе",
    color: "Silica White",
    colorUa: "Silica Білий",
    transmission: "7-Speed SSG",
    horsepower: 740,
    status: "In Stock",
    statusUa: "В наявності",
    verified: false,
    image: "https://images.unsplash.com/photo-1621135802920-133df287f89c?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1621135802920-133df287f89c?w=1200&q=90",
    ],
    features: ["Proactive Damping", "Carbon Fiber Monocoque", "Variable Drift Control", "McLaren Track Telemetry"],
    featuresUa: ["Проактивне демпфування", "Карбоновий монокок", "Контроль заносу", "McLaren телеметрія"],
    vin: "SBM13DCA4RW0XXXXX",
    doors: 2,
    seats: 2,
    seatMaterial: "Alcantara",
    seatMaterialUa: "Алькантара",
    safetyFeatures: ["ABS", "ESP", "4 Airbags", "Rear Camera"],
    comfortFeatures: ["Electric Seats", "Auto Climate", "Lift System"],
    infotainment: ["Apple CarPlay", "Bowers & Wilkins", "Navigation", "Track Telemetry"],
    condition: "Used",
    conditionUa: "Б/у",
    country: "United Kingdom",
    countryUa: "Великобританія",
    plateType: "Євро номери",
    history: [
      { date: "2024-04", event: "Factory Production", eventUa: "Виробництво", mileage: 0 },
      { date: "2024-06", event: "Delivered to Dealer", eventUa: "Доставлено дилеру", mileage: 20 },
      { date: "2024-07", event: "First Registration", eventUa: "Перша реєстрація", mileage: 40 },
    ],
  },
  {
    id: "9",
    make: "BMW",
    model: "XM Label Red",
    year: 2025,
    price: 185000,
    mileage: 600,
    engine: "4.4L Twin-Turbo V8 Hybrid",
    fuel: "Hybrid",
    fuelUa: "Гібрид",
    drive: "AWD",
    bodyType: "SUV",
    bodyTypeUa: "Позашляховик",
    color: "Toronto Red",
    colorUa: "Toronto Червоний",
    transmission: "8-Speed M Steptronic",
    horsepower: 738,
    status: "In Transit",
    statusUa: "В дорозі",
    verified: true,
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=90",
    ],
    features: ["M Carbon Exterior Package", "Bowers & Wilkins Diamond", "M Sport Exhaust", "Air Suspension"],
    featuresUa: ["M Карбон пакет", "Bowers & Wilkins Diamond", "M Sport вихлоп", "Пневмопідвіска"],
    vin: "5YMUJ0C03R9XXXXXX",
    doors: 5,
    seats: 5,
    seatMaterial: "Leather",
    seatMaterialUa: "Шкіра",
    safetyFeatures: ["ABS", "ESP", "8 Airbags", "Lane Assist", "Adaptive Cruise", "Cross Traffic Alert"],
    comfortFeatures: ["Heated Seats", "Ventilated Seats", "Massage Seats", "Panoramic Roof", "Air Suspension", "Heated Steering"],
    infotainment: ["iDrive 8", "Apple CarPlay", "Android Auto", "Bowers & Wilkins", "Navigation", "Head-Up Display", "Wireless Charging"],
    condition: "New",
    conditionUa: "Новий",
    country: "USA",
    countryUa: "США",
    plateType: "Без номерів",
    history: [
      { date: "2025-01", event: "Factory Production", eventUa: "Виробництво", mileage: 0 },
      { date: "2025-02", event: "Shipping", eventUa: "Відправка", mileage: 10 },
    ],
  },
  {
    id: "10",
    make: "Volkswagen",
    model: "Tiguan R-Line",
    year: 2024,
    price: 52000,
    mileage: 8200,
    engine: "2.0L TSI",
    fuel: "Petrol",
    fuelUa: "Бензин",
    drive: "AWD",
    bodyType: "SUV",
    bodyTypeUa: "Позашляховик",
    color: "Oryx White",
    colorUa: "Oryx Білий",
    transmission: "7-Speed DSG",
    horsepower: 245,
    status: "In Stock",
    statusUa: "В наявності",
    verified: true,
    image: "https://images.unsplash.com/photo-1606611013016-969c19ba27ea?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1606611013016-969c19ba27ea?w=1200&q=90",
    ],
    features: ["Digital Cockpit Pro", "IQ.DRIVE", "Panoramic Roof", "DCC Adaptive Suspension"],
    featuresUa: ["Digital Cockpit Pro", "IQ.DRIVE", "Панорамний дах", "DCC адаптивна підвіска"],
    vin: "WVGZZZE2ZRP0XXXXX",
    doors: 5,
    seats: 5,
    seatMaterial: "Combined",
    seatMaterialUa: "Комбінована",
    safetyFeatures: ["ABS", "ESP", "8 Airbags", "Lane Assist", "Front Assist", "Blind Spot Monitor"],
    comfortFeatures: ["Heated Seats", "Heated Steering", "Panoramic Roof", "Electric Tailgate", "DCC Suspension"],
    infotainment: ["MIB3", "Apple CarPlay", "Android Auto", "Navigation", "Wireless Charging"],
    condition: "Used",
    conditionUa: "Б/у",
    country: "Germany",
    countryUa: "Німеччина",
    plateType: "Українські номери",
    history: [
      { date: "2024-01", event: "Factory Production", eventUa: "Виробництво", mileage: 0 },
      { date: "2024-03", event: "Delivered to Dealer", eventUa: "Доставлено дилеру", mileage: 15 },
      { date: "2024-04", event: "First Registration", eventUa: "Перша реєстрація", mileage: 40 },
      { date: "2025-01", event: "Service Inspection", eventUa: "Сервісний огляд", mileage: 8200 },
    ],
  },
  {
    id: "11",
    make: "Toyota",
    model: "Camry Hybrid",
    year: 2024,
    price: 38500,
    mileage: 12000,
    engine: "2.5L Hybrid",
    fuel: "Hybrid",
    fuelUa: "Гібрид",
    drive: "FWD",
    bodyType: "Sedan",
    bodyTypeUa: "Седан",
    color: "Precious Silver",
    colorUa: "Срібний",
    transmission: "CVT",
    horsepower: 218,
    status: "In Stock",
    statusUa: "В наявності",
    verified: true,
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=1200&q=90",
    ],
    features: ["Toyota Safety Sense", "JBL Audio", "Wireless Charging", "Head-Up Display"],
    featuresUa: ["Toyota Safety Sense", "JBL аудіо", "Бездротова зарядка", "Проекційний дисплей"],
    vin: "4T1K61AK3RU0XXXXX",
    doors: 4,
    seats: 5,
    seatMaterial: "Fabric",
    seatMaterialUa: "Тканина",
    safetyFeatures: ["ABS", "ESP", "8 Airbags", "Lane Departure", "Pre-Collision System", "Adaptive Cruise"],
    comfortFeatures: ["Heated Seats", "Electric Driver Seat", "Auto Climate", "Rear USB"],
    infotainment: ["Toyota Touch", "Apple CarPlay", "Android Auto", "JBL", "Navigation"],
    condition: "Used",
    conditionUa: "Б/у",
    country: "Japan",
    countryUa: "Японія",
    plateType: "Українські номери",
    history: [
      { date: "2024-02", event: "Factory Production", eventUa: "Виробництво", mileage: 0 },
      { date: "2024-04", event: "First Registration", eventUa: "Перша реєстрація", mileage: 30 },
      { date: "2025-01", event: "Service Inspection", eventUa: "Сервісний огляд", mileage: 12000 },
    ],
  },
  {
    id: "12",
    make: "Mercedes-Benz",
    model: "G-Class 63 AMG",
    year: 2025,
    price: 224000,
    mileage: 300,
    engine: "4.0L Twin-Turbo V8",
    fuel: "Petrol",
    fuelUa: "Бензин",
    drive: "4WD",
    bodyType: "SUV",
    bodyTypeUa: "Позашляховик",
    color: "Obsidian Black",
    colorUa: "Обсидіан Чорний",
    transmission: "9-Speed AMG Speedshift",
    horsepower: 577,
    status: "In Stock",
    statusUa: "В наявності",
    verified: true,
    image: "https://images.unsplash.com/photo-1520031441872-265e4ff70366?w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1520031441872-265e4ff70366?w=1200&q=90",
    ],
    features: ["AMG Performance Exhaust", "Burmester Sound", "MBUX Hyperscreen", "Active Suspension"],
    featuresUa: ["AMG Performance вихлоп", "Burmester звук", "MBUX Hyperscreen", "Активна підвіска"],
    vin: "W1N4632B4RX0XXXXX",
    doors: 5,
    seats: 5,
    seatMaterial: "Leather",
    seatMaterialUa: "Шкіра",
    safetyFeatures: ["ABS", "ESP", "10 Airbags", "Active Brake Assist", "Blind Spot", "360 Camera"],
    comfortFeatures: ["Heated Seats", "Ventilated Seats", "Massage Seats", "Heated Steering", "Air Suspension"],
    infotainment: ["MBUX", "Apple CarPlay", "Android Auto", "Burmester", "Navigation", "Head-Up Display", "Wireless Charging"],
    condition: "New",
    conditionUa: "Новий",
    country: "Germany",
    countryUa: "Німеччина",
    plateType: "Без номерів",
    history: [
      { date: "2025-01", event: "Factory Production", eventUa: "Виробництво", mileage: 0 },
      { date: "2025-02", event: "Delivered", eventUa: "Доставлено", mileage: 20 },
    ],
  },
]

export const makes = ["Porsche", "BMW", "Mercedes-Benz", "Audi", "Lamborghini", "Ferrari", "McLaren", "Volkswagen", "Toyota", "Honda", "Hyundai", "Kia", "Nissan", "Mazda", "Skoda", "Volvo", "Lexus", "Land Rover", "Jeep", "Tesla"]
export const modelsByMake: Record<string, string[]> = {
  "Porsche": ["911 GT3 RS", "Taycan Turbo S", "Cayenne", "Macan", "Panamera", "911 Carrera"],
  "BMW": ["M4 CSL", "XM Label Red", "X5", "X3", "3 Series", "5 Series", "7 Series", "iX"],
  "Mercedes-Benz": ["AMG GT 63 S", "G-Class 63 AMG", "E-Class", "S-Class", "GLE", "GLC", "C-Class", "EQS"],
  "Audi": ["RS e-tron GT", "A6", "A4", "Q5", "Q7", "Q8", "e-tron", "RS6"],
  "Lamborghini": ["Huracan Tecnica", "Urus", "Revuelto"],
  "Ferrari": ["296 GTB", "SF90", "Roma", "F8 Tributo"],
  "McLaren": ["750S", "720S", "Artura"],
  "Volkswagen": ["Tiguan R-Line", "Golf", "Passat", "Touareg", "ID.4", "Arteon"],
  "Toyota": ["Camry Hybrid", "RAV4", "Land Cruiser", "Corolla", "Supra"],
  "Honda": ["Civic", "CR-V", "Accord", "HR-V"],
  "Hyundai": ["Tucson", "Santa Fe", "Ioniq 5", "Sonata"],
  "Kia": ["Sportage", "EV6", "Sorento", "Stinger"],
  "Nissan": ["Qashqai", "X-Trail", "Leaf", "Juke"],
  "Mazda": ["CX-5", "CX-60", "MX-5", "3"],
  "Skoda": ["Octavia", "Superb", "Kodiaq", "Enyaq"],
  "Volvo": ["XC60", "XC90", "S60", "V60"],
  "Lexus": ["RX", "NX", "ES", "LC"],
  "Land Rover": ["Range Rover", "Defender", "Discovery"],
  "Jeep": ["Wrangler", "Grand Cherokee", "Compass"],
  "Tesla": ["Model 3", "Model Y", "Model S", "Model X"],
}
export const bodyTypes = ["Купе", "Седан", "Позашляховик", "Хетчбек", "Універсал", "Кабріолет", "Мінівен", "Пікап"]
export const bodyTypesMap: Record<string, string> = { "Купе": "Coupe", "Седан": "Sedan", "Позашляховик": "SUV", "Хетчбек": "Hatchback", "Універсал": "Wagon", "Кабріолет": "Convertible", "Мінівен": "Minivan", "Пікап": "Pickup" }
export const fuelTypes = ["Бензин", "Дизель", "Електро", "Гібрид", "Plug-in Гібрид", "Газ/Бензин"]
export const fuelTypesMap: Record<string, string> = { "Бензин": "Petrol", "Дизель": "Diesel", "Електро": "Electric", "Гібрид": "Hybrid", "Plug-in Гібрид": "Plug-in Hybrid", "Газ/Бензин": "LPG" }
export const driveTypes = ["FWD", "RWD", "AWD", "4WD"]
export const driveLabels: Record<string, string> = { "FWD": "Передній", "RWD": "Задній", "AWD": "Повний (AWD)", "4WD": "Повний (4WD)" }
export const transmissionTypes = ["Автомат", "Механіка", "Робот", "Варіатор"]
export const conditionTypes = ["Новий", "Б/у", "Сертифікований"]
export const countries = ["Німеччина", "США", "Японія", "Італія", "Великобританія", "Франція", "Корея", "Чехія", "Швеція"]

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("uk-UA", {
    style: "currency",
    currency: "EUR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price)
}

export function formatMileage(mileage: number): string {
  return new Intl.NumberFormat("uk-UA").format(mileage) + " km"
}
